openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  '/products/{productId}':
    parameters:
      - schema:
          type: string
        name: productId
        in: path
        required: true
    get:
      summary: Get product detail
      tags: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
              examples: {}
      operationId: getProduct
      description: ''
  /products:
    get:
      summary: List of products
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
      operationId: getProducts
components:
  schemas:
    Book:
      title: Book
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        author:
          type: string
        genre:
          type: string
        height:
          type: integer
        publisher:
          type: string
  responses: {}
