openapi: 3.0.0
info:
  title: Product API
  version: 1.2.0
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  '/products/{productId}':
    parameters:
      - schema:
          type: string
        name: productId
        in: path
        required: true
    get:
      summary: Get product detail
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
      operationId: getProduct
      description: ''
      tags:
        - product
    delete:
      summary: ''
      operationId: deleteProduct
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
    post:
      summary: ''
      operationId: postProduct
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductRequest'
  /products:
    get:
      summary: List of products
      tags:
        - product
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductsList'
      operationId: getProducts
      parameters:
        - schema:
            type: integer
            format: int32
          in: query
          name: page
        - schema:
            type: integer
            format: int32
            default: 10
          in: query
          name: size
components:
  schemas:
    Product:
      title: Product
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        author:
          type: string
        genre:
          type: string
        height:
          type: integer
        publisher:
          type: string
    ProductRequest:
      title: ProductRequest
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        author:
          type: string
        genre:
          type: string
        height:
          type: integer
        publisher:
          type: string
    GenericResponse:
      title: GenericResponse
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        data:
          type: object
    MetaResponse:
      title: MetaResponse
      type: object
      properties:
        totalPages:
          type: string
        totalElements:
          type: string
        size:
          type: string
        page:
          type: string
        numberOfElements:
          type: string
    ProductsList:
      title: ProductList
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        meta:
          $ref: '#/components/schemas/MetaResponse'
  responses: {}
